### ISSUE TITLE
Add Readme to the repository

### ISSUE THREAD

**Issue by ashwini0529** [ashwini0529/lastdayofhacktoberfest#1]

**Comment by tatendamarshall210** [comment]
Readme``

**Comment by SarthakDandotiya** [comment]
# LastDayOfHacktoberfest

This repo is for last day commits for hacktoberfest

**Comment by ashwini0529** [comment]
Please open up a PR. I'll merge

**Comment by dharmang** [comment]
Hi @ashwini0529 ,
Cannot fork because repository is empty.
Create at least one file in the repository by yourself first.
